# Generated by Django 4.0.4 on 2022-05-29 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_fecha_cambio_oferta_date_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 2, 50, 13, 562307)),
        ),
    ]
