# Generated by Django 4.0.4 on 2022-05-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_ask', models.CharField(max_length=60)),
                ('who_resp', models.CharField(max_length=60)),
                ('fecha_cambio', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.TimeField(auto_now_add=True)),
                ('who_ask', models.CharField(max_length=60)),
            ],
        ),
    ]
