# Generated by Django 4.0.4 on 2022-05-29 00:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='who_ask',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fecha_solicitud',
        ),
        migrations.AddField(
            model_name='oferta',
            name='id_ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha',
            field=models.TimeField(default=datetime.datetime(2022, 5, 29, 0, 44, 7, 992160)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='who_resp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='who_ask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
