# Generated by Django 4.0.4 on 2022-05-29 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ticket_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_cambio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
