# Generated by Django 4.0.4 on 2022-05-29 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_oferta_fecha_cambio_alter_ticket_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.CharField(default='En espera', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 2, 58, 59, 940840)),
        ),
    ]
